---
title: "Model Summary"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### State model




$$z_{i,t} \sim binom(\phi_{i,t}, z_{i,t-1})$$
$$logit(\phi_{i,t}) = \mu_{\phi} + \beta_{\phi}*TIME_{t} + \epsilon_{\phi t}$$

where $z$ is the true state of the chicks (i.e., 0,1,2) and $TIME$ is really just relative chick age. The is assuming a single year and a single site. We are estimating two general parameters here ($\mu_{\phi}$ and $\beta_{\phi}$) as well as an $\epsilon_\phi$ for each time step. So there is replication at the nest level here (not time step level).


### Observation model

$$y_{i,t} \sim binom(p_{i,t}*w_{i,t}, z_{i,t})$$
$$logit(p_{i,t}) = \mu_{p} + \beta_{p}*TIME_{t} + \epsilon_{pi}$$

where $y$ is the observed state (i.e., 0,1,2,) and $w$ is a binary for day/night (actual day/night fed into the model). That way each time step can be modeled but the $w$ index will ensure that the $p$ isn't impacted because it was simply night and there's no way to see the penguins (Chris came up with that). We need to model each time step because survival is from one hour to the next. We are estimating two general parameters here ($\mu_{p}$ and $\beta_{p}$) as well as an $\epsilon_p$ for each time nest So there is replication at the time step level here (not nest level).


### Priors

$$\mu_{p} = logit(m_{p})$$
$$\mu_{\phi} = logit(m_{\phi})$$
$$m_{p} \sim beta (1.5, 1.5)$$
$$m_{\phi} \sim beta (1.5, 1.5)$$
$$\beta_{\phi} \sim N(0, 100) T(0,1)$$
$$\beta_{p} \sim N(0, 10) T(0,1)$$
$$\epsilon_{pi} \sim N(0, \tau_{p}) T(-10,10)$$
$$\epsilon_{\phi i} \sim N(0, \tau_{\phi}) T(-10,10)$$
$$\tau_p = \frac{1}{\sigma_{p}^2}$$
$$\tau_\phi = \frac{1}{\sigma_{\phi}^2}$$
$$\sigma_p \sim unif(0,10)$$
$$\sigma_\phi \sim unif(0,10)$$


### Next steps

When adding covariates I think it should look something like below. I think the $\beta_{1}$ should stay in there, because it's focing the model to account for chick age when measuring survival due to those other factors:

$$z_{i,t} \sim binom(\phi_{i,t}, z_{i,t-1})$$
$$logit(\phi_{i,t}) = \mu_{\phi} + \beta_{1\phi}*TIME_{t} + \beta_{2\phi}*SIC_{t} + \beta_{3\phi}*KRILL_{t} + \epsilon_{\phi t}$$
$$y_{i,t} \sim binom(p_{i,t}*w_{i,j}, z_{i,t})$$
$$logit(p_{i,t}) = \mu_{p} + \beta_{p}*TIME_{t} + \epsilon_{pi}$$


When modeling a single year but multile sites, all nests could be modeled together, with the $\mu_{\phi}$, $\beta_{1\phi}$, $\beta_{2\phi}$, $\beta_{3\phi}$, and $\epsilon_{\phi t}$ parameters modeled with random site effects. I don't think the parameters associated with $p$ should get a random effect, because detection is already being modeled with nest identity as a random effect - no need to add on a site level as well.

I suppose it's a little more complicated than this, since we don't have covariates at the hourly time scale (except maybe temperature from the cameras). The effect of covariates on survival would have to be modeled at the day/week level (I guess hierarchically where each day or week is a 'group'?). Or would it be better just to replicate the KRILL value for every hour within a week, for instance?

When modeling multiple years and multiple sites, I guess the $\mu_{\phi}$, $\beta_{1\phi}$, $\beta_{2\phi}$, $\beta_{3\phi}$, and $\epsilon_{\phi t}$ parameters should be modeled with random effect for site AND a random effect for year?


