#!/bin/bash

#PBS -l nodes=1:ppn=28,walltime=4:00:00
#PBS -q short
#PBS -N PW_run
#PBS -j oe
#PBS -o out.txt

module load shared
module load R/3.4.4
module load gcc-stack
module load openblas/dynamic/0.2.18
module load lapack/gcc/64/3.6.0
module load JAGS/4.3.0
module load gnu-parallel/6.0

export R_LIBS=/gpfs/home/cyoungflesh/R_libs

cd /gpfs/home/cyoungflesh/penguin_watch_model/Scripts

Rscript 4-model.R

# parallel < 4-par-run.txt

